# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(850, 532)
        Form.setStyleSheet("/*https://www.realtimecolors.com/?colors=e0edf7-020608-97c5e3-203279-4c54cf&fonts=Inter-Inter*/\n"
"\n"
"color:#e0edf7;")
        self.main = QtWidgets.QFrame(Form)
        self.main.setGeometry(QtCore.QRect(10, 20, 831, 501))
        self.main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main.setObjectName("main")
        self.bg_main = QtWidgets.QLabel(self.main)
        self.bg_main.setGeometry(QtCore.QRect(0, 0, 831, 501))
        self.bg_main.setStyleSheet("background-color: rgb(5, 15, 20);\n"
"\n"
"border-bottom-left-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.bg_main.setText("")
        self.bg_main.setObjectName("bg_main")
        self.label_2 = QtWidgets.QLabel(self.main)
        self.label_2.setGeometry(QtCore.QRect(226, 0, 51, 501))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:1, stop:0 rgba(0, 0, 0, 150), stop:1 rgba(255, 255, 255, 0));")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.main)
        self.label_3.setGeometry(QtCore.QRect(503, 0, 51, 501))
        self.label_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:1, stop:0 rgba(0, 0, 0, 150), stop:1 rgba(255, 255, 255, 0));")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.main)
        self.label_4.setGeometry(QtCore.QRect(0, 20, 277, 51))
        self.label_4.setStyleSheet("font: 81 20pt \"Montserrat ExtraBold\";\n"
"font-weight:bold;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.main)
        self.label_5.setGeometry(QtCore.QRect(277, 20, 277, 51))
        self.label_5.setStyleSheet("font: 81 20pt \"Montserrat ExtraBold\";\n"
"font-weight:bold;\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.main)
        self.label_6.setGeometry(QtCore.QRect(554, 20, 277, 51))
        self.label_6.setStyleSheet("font: 81 20pt \"Montserrat ExtraBold\";\n"
"font-weight:bold;\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.github = QtWidgets.QPushButton(self.main)
        self.github.setEnabled(True)
        self.github.setGeometry(QtCore.QRect(38, 210, 200, 71))
        self.github.setStyleSheet(".QPushButton{\n"
"background-color: rgb(0, 154, 255);\n"
"border-radius:6px;\n"
"margin:1px;\n"
"    font: 63 15pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
".QPushButton::hover{\n"
"background-color: rgb(0, 113, 188);\n"
"}\n"
"\n"
".QPushButton::disabled{\n"
"background-color:grey;\n"
"}\n"
"\n"
".QPushButton::pressed{\n"
"margin:0px;\n"
"}")
        self.github.setObjectName("github")
        self.attach_game = QtWidgets.QPushButton(self.main)
        self.attach_game.setEnabled(False)
        self.attach_game.setGeometry(QtCore.QRect(315, 210, 200, 71))
        self.attach_game.setStyleSheet(".QPushButton{\n"
"background-color: rgb(0, 154, 255);\n"
"border-radius:6px;\n"
"margin:1px;\n"
"    font: 63 15pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
".QPushButton::hover{\n"
"background-color: rgb(0, 113, 188);\n"
"}\n"
"\n"
".QPushButton::disabled{\n"
"background-color:grey;\n"
"}\n"
"\n"
".QPushButton::pressed{\n"
"margin:0px;\n"
"}")
        self.attach_game.setObjectName("attach_game")
        self.clickme = QtWidgets.QPushButton(self.main)
        self.clickme.setEnabled(False)
        self.clickme.setGeometry(QtCore.QRect(592, 210, 200, 71))
        self.clickme.setStyleSheet(".QPushButton{\n"
"background-color: rgb(0, 154, 255);\n"
"border-radius:6px;\n"
"margin:1px;\n"
"    font: 63 15pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
".QPushButton::hover{\n"
"background-color: rgb(0, 113, 188);\n"
"}\n"
"\n"
".QPushButton::disabled{\n"
"background-color:grey;\n"
"}\n"
"\n"
".QPushButton::pressed{\n"
"margin:0px;\n"
"}")
        self.clickme.setObjectName("clickme")
        self.status = QtWidgets.QLabel(self.main)
        self.status.setGeometry(QtCore.QRect(59, 180, 191, 20))
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setObjectName("status")
        self.statusCircle = QtWidgets.QLabel(self.main)
        self.statusCircle.setGeometry(QtCore.QRect(95, 180, 21, 21))
        self.statusCircle.setStyleSheet("background-color: rgb(255, 0, 4);\n"
"border-radius:10px;")
        self.statusCircle.setText("")
        self.statusCircle.setAlignment(QtCore.Qt.AlignCenter)
        self.statusCircle.setObjectName("statusCircle")
        self.attach_status = QtWidgets.QLabel(self.main)
        self.attach_status.setGeometry(QtCore.QRect(320, 180, 191, 20))
        self.attach_status.setAlignment(QtCore.Qt.AlignCenter)
        self.attach_status.setObjectName("attach_status")
        self.backup_button = QtWidgets.QPushButton(self.main)
        self.backup_button.setEnabled(False)
        self.backup_button.setGeometry(QtCore.QRect(662, 450, 161, 41))
        self.backup_button.setStyleSheet(".QPushButton{\n"
"background-color: rgb(0, 154, 255);\n"
"border-radius:6px;\n"
"margin:1px;\n"
"    font: 63 15pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
".QPushButton::hover{\n"
"background-color: rgb(0, 113, 188);\n"
"}\n"
"\n"
".QPushButton::disabled{\n"
"background-color:grey;\n"
"}\n"
"\n"
".QPushButton::pressed{\n"
"margin:0px;\n"
"}")
        self.backup_button.setObjectName("backup_button")
        self.DeleteRepos = QtWidgets.QCheckBox(self.main)
        self.DeleteRepos.setGeometry(QtCore.QRect(20, 456, 241, 31))
        self.DeleteRepos.setStyleSheet("QCheckBox {\n"
"    spacing: 6px;\n"
"    border: none;\n"
"    background: transparent;\n"
"    color: #FFFFFF;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: 2px solid rgb(0, 154, 255);\n"
"    border-radius: 3px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border-color: rgb(0, 78, 126)\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(0, 154, 255);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    background-color: #005fa3;\n"
"    border-color: #005fa3;\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled {\n"
"    border-color: #ccc;\n"
"    background-color: #eee;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:disabled {\n"
"    background-color: #bbb;\n"
"    border-color: #bbb;\n"
"}\n"
"")
        self.DeleteRepos.setObjectName("DeleteRepos")
        self.overlay = QtWidgets.QFrame(self.main)
        self.overlay.setGeometry(QtCore.QRect(-20, 10000, 851, 511))
        self.overlay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.overlay.setFrameShadow(QtWidgets.QFrame.Raised)
        self.overlay.setObjectName("overlay")
        self.overlaybg = QtWidgets.QLabel(self.overlay)
        self.overlaybg.setGeometry(QtCore.QRect(-134, -58, 1111, 581))
        self.overlaybg.setStyleSheet("background-color: rgba(5, 15, 20, 200);")
        self.overlaybg.setText("")
        self.overlaybg.setObjectName("overlaybg")
        self.progress_bar = QtWidgets.QProgressBar(self.overlay)
        self.progress_bar.setGeometry(QtCore.QRect(190, 240, 491, 23))
        self.progress_bar.setStyleSheet(".QProgressBar {\n"
"border-color: #203279;\n"
"    border-radius: 4px;\n"
"    color:rgba(0, 0, 0, 0);\n"
"    text-align: center;\n"
"border:3px solid #203279;\n"
"border-radius:6px;\n"
"}\n"
"\n"
".QProgressBar::chunk {\n"
"    background-color:#203279;\n"
"    width: 5px;\n"
"    margin: 0px;\n"
"    border-radius:1px;\n"
"}")
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.label_7 = QtWidgets.QLabel(self.overlay)
        self.label_7.setGeometry(QtCore.QRect(190, 110, 491, 61))
        self.label_7.setStyleSheet("font: 81 20pt \"Montserrat ExtraBold\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.progress_message = QtWidgets.QLabel(self.overlay)
        self.progress_message.setGeometry(QtCore.QRect(190, 170, 491, 61))
        self.progress_message.setStyleSheet("font: 81 15pt \"Montserrat ExtraBold\";")
        self.progress_message.setAlignment(QtCore.Qt.AlignCenter)
        self.progress_message.setObjectName("progress_message")
        self.shuffle_arena = QtWidgets.QPushButton(self.main)
        self.shuffle_arena.setEnabled(False)
        self.shuffle_arena.setGeometry(QtCore.QRect(620, 190, 151, 31))
        self.shuffle_arena.setStyleSheet(".QPushButton{\n"
"background-color: rgb(0, 154, 255);\n"
"border-radius:6px;\n"
"border:2px solid rgb(5, 15, 20);\n"
"margin:1px;\n"
"    font: 63 12pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
".QPushButton::hover{\n"
"background-color: rgb(0, 113, 188);\n"
"}\n"
"\n"
".QPushButton::disabled{\n"
"background-color:grey;\n"
"}\n"
"\n"
".QPushButton::pressed{\n"
"margin:0px;\n"
"}")
        self.shuffle_arena.setObjectName("shuffle_arena")
        self.titlebar_cont = QtWidgets.QFrame(Form)
        self.titlebar_cont.setGeometry(QtCore.QRect(10, 0, 831, 21))
        self.titlebar_cont.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titlebar_cont.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titlebar_cont.setObjectName("titlebar_cont")
        self.bg_titlebar = QtWidgets.QLabel(self.titlebar_cont)
        self.bg_titlebar.setGeometry(QtCore.QRect(0, 0, 831, 31))
        self.bg_titlebar.setStyleSheet("background-color:#0a1f29;\n"
"border-top-left-radius:10px;\n"
"border-top-right-radius:10px;")
        self.bg_titlebar.setText("")
        self.bg_titlebar.setObjectName("bg_titlebar")
        self.close_but = QtWidgets.QPushButton(self.titlebar_cont)
        self.close_but.setGeometry(QtCore.QRect(800, 0, 31, 23))
        self.close_but.setStyleSheet("font: 20pt \"Matura MT Script Capitals\";\n"
"color:#e0edf7;\n"
"background-color:transparent;")
        self.close_but.setObjectName("close_but")
        self.mini_but = QtWidgets.QPushButton(self.titlebar_cont)
        self.mini_but.setGeometry(QtCore.QRect(770, 0, 31, 23))
        self.mini_but.setStyleSheet("font: 20pt \"Matura MT Script Capitals\";\n"
"color:#e0edf7;\n"
"background-color:transparent;")
        self.mini_but.setObjectName("mini_but")
        self.label = QtWidgets.QLabel(self.titlebar_cont)
        self.label.setGeometry(QtCore.QRect(9, -1, 301, 21))
        self.label.setStyleSheet("font: 5 12pt \"Montserrat Medium\";")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Connect Github"))
        self.label_5.setText(_translate("Form", "Attach to SKATE 3"))
        self.label_6.setText(_translate("Form", "Click!"))
        self.github.setText(_translate("Form", "Connect"))
        self.attach_game.setText(_translate("Form", "Attach"))
        self.clickme.setText(_translate("Form", "CLICK ME"))
        self.status.setText(_translate("Form", "Disconnected"))
        self.attach_status.setText(_translate("Form", "Not attached"))
        self.backup_button.setText(_translate("Form", "Load backup"))
        self.DeleteRepos.setText(_translate("Form", "DELETE OLD REPOS"))
        self.label_7.setText(_translate("Form", "Loading..."))
        self.progress_message.setText(_translate("Form", "Message"))
        self.shuffle_arena.setText(_translate("Form", "shuffle textures"))
        self.close_but.setText(_translate("Form", "x"))
        self.mini_but.setText(_translate("Form", "-"))
        self.label.setText(_translate("Form", "UWU"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
