# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(670, 335)
        self.message = QtWidgets.QLabel(Form)
        self.message.setGeometry(QtCore.QRect(70, 80, 521, 101))
        self.message.setStyleSheet("font: 81 15pt \"Montserrat ExtraBold\";\n"
"font-weight:bold;\n"
"color:white;")
        self.message.setAlignment(QtCore.Qt.AlignCenter)
        self.message.setWordWrap(True)
        self.message.setObjectName("message")
        self.bg_main = QtWidgets.QLabel(Form)
        self.bg_main.setGeometry(QtCore.QRect(70, 80, 521, 181))
        self.bg_main.setStyleSheet("background-color: rgb(14, 42, 56);\n"
"\n"
"border-bottom-left-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.bg_main.setText("")
        self.bg_main.setObjectName("bg_main")
        self.ok_button = QtWidgets.QPushButton(Form)
        self.ok_button.setEnabled(True)
        self.ok_button.setGeometry(QtCore.QRect(230, 180, 200, 51))
        self.ok_button.setStyleSheet(".QPushButton{\n"
"background-color: rgb(0, 154, 255);\n"
"border-radius:6px;\n"
"margin:1px;\n"
"    font: 63 15pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
".QPushButton::hover{\n"
"background-color: rgb(0, 113, 188);\n"
"}\n"
"\n"
".QPushButton::disabled{\n"
"background-color:grey;\n"
"}\n"
"\n"
".QPushButton::pressed{\n"
"margin:0px;\n"
"}")
        self.ok_button.setObjectName("ok_button")
        self.titlebar_cont = QtWidgets.QFrame(Form)
        self.titlebar_cont.setGeometry(QtCore.QRect(70, 60, 831, 21))
        self.titlebar_cont.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titlebar_cont.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titlebar_cont.setObjectName("titlebar_cont")
        self.bg_titlebar = QtWidgets.QLabel(self.titlebar_cont)
        self.bg_titlebar.setGeometry(QtCore.QRect(0, 0, 521, 31))
        self.bg_titlebar.setStyleSheet("background-color:#0a1f29;\n"
"border-top-left-radius:10px;\n"
"border-top-right-radius:10px;")
        self.bg_titlebar.setText("")
        self.bg_titlebar.setObjectName("bg_titlebar")
        self.close_but = QtWidgets.QPushButton(self.titlebar_cont)
        self.close_but.setGeometry(QtCore.QRect(490, 0, 31, 23))
        self.close_but.setStyleSheet("font: 20pt \"Matura MT Script Capitals\";\n"
"color:#e0edf7;\n"
"background-color:transparent;")
        self.close_but.setObjectName("close_but")
        self.mini_but = QtWidgets.QPushButton(self.titlebar_cont)
        self.mini_but.setGeometry(QtCore.QRect(770, 0, 31, 23))
        self.mini_but.setStyleSheet("font: 20pt \"Matura MT Script Capitals\";\n"
"color:#e0edf7;\n"
"background-color:transparent;")
        self.mini_but.setObjectName("mini_but")
        self.popup_title = QtWidgets.QLabel(self.titlebar_cont)
        self.popup_title.setGeometry(QtCore.QRect(9, -1, 301, 21))
        self.popup_title.setStyleSheet("font: 5 12pt \"Montserrat Medium\";\n"
"color:white;")
        self.popup_title.setObjectName("popup_title")
        self.shadow = QtWidgets.QLabel(Form)
        self.shadow.setGeometry(QtCore.QRect(76, 67, 521, 201))
        self.shadow.setStyleSheet("background-color: rgba(5, 15, 20, 100);\n"
"\n"
"border-radius:10px;")
        self.shadow.setText("")
        self.shadow.setObjectName("shadow")
        self.shadow.raise_()
        self.bg_main.raise_()
        self.message.raise_()
        self.ok_button.raise_()
        self.titlebar_cont.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.message.setText(_translate("Form", "MESSAGE"))
        self.ok_button.setText(_translate("Form", "ok"))
        self.close_but.setText(_translate("Form", "x"))
        self.mini_but.setText(_translate("Form", "-"))
        self.popup_title.setText(_translate("Form", "Popup"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
