# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'too many textures.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(509, 1243)
        Form.setStyleSheet("/*https://www.realtimecolors.com/?colors=e0edf7-020608-97c5e3-203279-4c54cf&fonts=Inter-Inter*/\n"
"\n"
"color:#e0edf7;\n"
"font: 63 13pt \"Montserrat SemiBold\";")
        self.main = QtWidgets.QFrame(Form)
        self.main.setGeometry(QtCore.QRect(10, 20, 491, 501))
        self.main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main.setObjectName("main")
        self.bg_main = QtWidgets.QLabel(self.main)
        self.bg_main.setGeometry(QtCore.QRect(0, 0, 491, 501))
        self.bg_main.setStyleSheet("background-color: rgb(5, 15, 20);\n"
"\n"
"border-bottom-left-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.bg_main.setText("")
        self.bg_main.setObjectName("bg_main")
        self.done_button = QtWidgets.QPushButton(self.main)
        self.done_button.setEnabled(False)
        self.done_button.setGeometry(QtCore.QRect(407, 10, 75, 41))
        self.done_button.setStyleSheet(".QPushButton{\n"
"background-color: rgb(0, 154, 255);\n"
"border-radius:6px;\n"
"margin:1px;\n"
"    font: 63 13pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
".QPushButton::hover{\n"
"background-color: rgb(0, 113, 188);\n"
"}\n"
"\n"
".QPushButton::disabled{\n"
"background-color:grey;\n"
"}\n"
"\n"
".QPushButton::pressed{\n"
"margin:0px;\n"
"}")
        self.done_button.setObjectName("done_button")
        self.checkbox_cont = QtWidgets.QFrame(self.main)
        self.checkbox_cont.setGeometry(QtCore.QRect(1000, 60, 491, 71))
        self.checkbox_cont.setStyleSheet("")
        self.checkbox_cont.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.checkbox_cont.setFrameShadow(QtWidgets.QFrame.Raised)
        self.checkbox_cont.setObjectName("checkbox_cont")
        self.asset_name = QtWidgets.QCheckBox(self.checkbox_cont)
        self.asset_name.setGeometry(QtCore.QRect(10, 6, 461, 61))
        self.asset_name.setStyleSheet("QCheckBox {\n"
"    spacing: 8px;\n"
"    color: white;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 36px;\n"
"    height: 36px;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 3px;\n"
"    background: #fff;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 1px solid #666;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #0078d7;\n"
"    image: url(:/icons/checkmark.svg);  /* Optional: Your checkmark icon */\n"
"    border: 1px solid #0078d7;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    background-color: #0063b1;\n"
"    border: 1px solid #0063b1;\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled {\n"
"    background: #ddd;\n"
"    border: 1px solid #ccc;\n"
"}\n"
"")
        self.asset_name.setObjectName("asset_name")
        self.shadow = QtWidgets.QLabel(self.checkbox_cont)
        self.shadow.setEnabled(True)
        self.shadow.setGeometry(QtCore.QRect(0, 10, 491, 61))
        self.shadow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 0));")
        self.shadow.setText("")
        self.shadow.setObjectName("shadow")
        self.shadow.raise_()
        self.asset_name.raise_()
        self.texture_count = QtWidgets.QLabel(self.main)
        self.texture_count.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.texture_count.setStyleSheet("color:red;")
        self.texture_count.setAlignment(QtCore.Qt.AlignCenter)
        self.texture_count.setObjectName("texture_count")
        self.titlebar_cont = QtWidgets.QFrame(Form)
        self.titlebar_cont.setGeometry(QtCore.QRect(10, 0, 491, 21))
        self.titlebar_cont.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titlebar_cont.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titlebar_cont.setObjectName("titlebar_cont")
        self.bg_titlebar = QtWidgets.QLabel(self.titlebar_cont)
        self.bg_titlebar.setGeometry(QtCore.QRect(0, 0, 491, 31))
        self.bg_titlebar.setStyleSheet("background-color:#0a1f29;\n"
"border-top-left-radius:10px;\n"
"border-top-right-radius:10px;")
        self.bg_titlebar.setText("")
        self.bg_titlebar.setObjectName("bg_titlebar")
        self.close_but = QtWidgets.QPushButton(self.titlebar_cont)
        self.close_but.setGeometry(QtCore.QRect(460, 0, 31, 23))
        self.close_but.setStyleSheet("font: 20pt \"Matura MT Script Capitals\";\n"
"color:#e0edf7;\n"
"background-color:transparent;")
        self.close_but.setObjectName("close_but")
        self.mini_but = QtWidgets.QPushButton(self.titlebar_cont)
        self.mini_but.setGeometry(QtCore.QRect(430, 0, 31, 23))
        self.mini_but.setStyleSheet("font: 20pt \"Matura MT Script Capitals\";\n"
"color:#e0edf7;\n"
"background-color:transparent;")
        self.mini_but.setObjectName("mini_but")
        self.label = QtWidgets.QLabel(self.titlebar_cont)
        self.label.setGeometry(QtCore.QRect(9, -1, 311, 21))
        self.label.setStyleSheet("font: 5 12pt \"Montserrat Medium\";")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.done_button.setText(_translate("Form", "Done"))
        self.asset_name.setText(_translate("Form", "ASSET NAME: TEXTURE NAME"))
        self.texture_count.setText(_translate("Form", "0/5"))
        self.close_but.setText(_translate("Form", "x"))
        self.mini_but.setText(_translate("Form", "-"))
        self.label.setText(_translate("Form", "UWU"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
